name: Your New Jekyll Site
markdown: redcarpet
pygments: true
prose:
  rooturl: '_posts'
  siteurl: 'st-peters-001.github.io'
ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
